services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: vidmadjar/traffictwin-server:latest  
    container_name: traffic_twin_app2
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongo-data:
